/* eslint-disable no-unused-vars */
export const MENU_STATE = {
  CAR: {
    MENU: 'Mobil',
    PAGE_TITLE: 'Mobil',
    DESCRIPTION: 'Daftar Mobil',
    PAGE_TITLE_CREATE: 'Tambah Mobil',
    PAGE_TITLE_EDIT: 'Edit Mobil',
    PAGE_TITLE_DETAIL: 'Detail Mobil',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  TRANSACTION: {
    MENU: 'Peminjaman',
    PAGE_TITLE: 'Peminjaman',
    DESCRIPTION: 'Riwayat Peminjaman',
    PAGE_TITLE_CREATE: 'Tambah Peminjaman',
    PAGE_TITLE_EDIT: 'Edit Peminjaman',
    PAGE_TITLE_DETAIL: 'Detail Peminjaman',
    BUTTON_CREATE: 'Pinjaman Baru',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  RETURN_TRANSACTION: {
    MENU: 'Pengembalian',
    PAGE_TITLE: 'Pengembalian',
    DESCRIPTION: 'Riwayat Pengembalian',
    PAGE_TITLE_CREATE: 'Tambah Pengembalian',
    PAGE_TITLE_EDIT: 'Edit Pengembalian',
    PAGE_TITLE_DETAIL: 'Detail Pengembalian',
    BUTTON_CREATE: 'Proses Pengembalian ',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
};
