/* eslint-disable no-unused-vars */
export const MENU_STATE = {
  CATEGORY_EMPLOYEE: {
    MENU: 'Kategori',
    PAGE_TITLE: 'Kategori',
    DESCRIPTION: 'Daftar Kategori',
    PAGE_TITLE_CREATE: 'Tambah Kategori',
    PAGE_TITLE_EDIT: 'Edit Kategori',
    PAGE_TITLE_DETAIL: 'Detail Kategori',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  JOB_POSITION: {
    MENU: 'Posisi',
    PAGE_TITLE: 'Posisi',
    DESCRIPTION: 'Daftar Posisi',
    PAGE_TITLE_CREATE: 'Tambah Posisi',
    PAGE_TITLE_EDIT: 'Edit Posisi',
    PAGE_TITLE_DETAIL: 'Detail Posisi',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  BRANCH: {
    MENU: 'Cabang',
    PAGE_TITLE: 'Cabang',
    DESCRIPTION: 'Daftar Cabang',
    PAGE_TITLE_CREATE: 'Tambah Cabang',
    PAGE_TITLE_EDIT: 'Edit Cabang',
    PAGE_TITLE_DETAIL: 'Detail Cabang',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  NPP: {
    MENU: 'Npp',
    PAGE_TITLE: 'Npp',
    DESCRIPTION: 'Daftar Npp',
    PAGE_TITLE_CREATE: 'Tambah Npp',
    PAGE_TITLE_EDIT: 'Edit Npp',
    PAGE_TITLE_DETAIL: 'Detail Npp',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  SHIFT: {
    MENU: 'Shift',
    PAGE_TITLE: 'Shift',
    DESCRIPTION: 'Daftar Shift',
    PAGE_TITLE_CREATE: 'Tambah Shift',
    PAGE_TITLE_EDIT: 'Edit Shift',
    PAGE_TITLE_DETAIL: 'Detail Shift',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  SCHEDULE: {
    MENU: 'Jadwal',
    PAGE_TITLE: 'Jadwal',
    DESCRIPTION: 'Daftar Jadwal',
    PAGE_TITLE_CREATE: 'Tambah Jadwal',
    PAGE_TITLE_EDIT: 'Edit Jadwal',
    PAGE_TITLE_DETAIL: 'Detail Jadwal',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  EMPLOYEE: {
    MENU: 'Karyawan',
    PAGE_TITLE: 'Karyawan',
    DESCRIPTION: 'Daftar Karyawan',
    PAGE_TITLE_CREATE: 'Tambah Karyawan',
    PAGE_TITLE_EDIT: 'Edit Karyawan',
    PAGE_TITLE_DETAIL: 'Detail Karyawan',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  TAX: {
    MENU: 'Pajak',
    PAGE_TITLE: 'Pajak',
    DESCRIPTION: 'Daftar Pajak',
    PAGE_TITLE_CREATE: 'Tambah Pajak',
    PAGE_TITLE_EDIT: 'Edit Pajak',
    PAGE_TITLE_DETAIL: 'Detail Pajak',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  LEAVE_TYPE: {
    MENU: 'Jenis Izin',
    PAGE_TITLE: 'Jenis Izin',
    DESCRIPTION: 'Daftar Jenis Izin',
    PAGE_TITLE_CREATE: 'Tambah Jenis Izin',
    PAGE_TITLE_EDIT: 'Edit Jenis Izin',
    PAGE_TITLE_DETAIL: 'Detail Jenis Izin',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  DEPARTMENT: {
    MENU: 'Departemen',
    PAGE_TITLE: 'Departemen',
    DESCRIPTION: 'Daftar Departemen',
    PAGE_TITLE_CREATE: 'Tambah Departemen',
    PAGE_TITLE_EDIT: 'Edit Departemen',
    PAGE_TITLE_DETAIL: 'Detail Departemen',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  BONUS: {
    MENU: 'Bonus',
    PAGE_TITLE: 'Bonus',
    DESCRIPTION: 'Daftar Bonus',
    PAGE_TITLE_CREATE: 'Tambah Bonus',
    PAGE_TITLE_EDIT: 'Edit Bonus',
    PAGE_TITLE_DETAIL: 'Detail Bonus',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  DEDUCTION: {
    MENU: 'Potongan',
    PAGE_TITLE: 'Potongan',
    DESCRIPTION: 'Daftar Potongan',
    PAGE_TITLE_CREATE: 'Tambah Potongan',
    PAGE_TITLE_EDIT: 'Edit Potongan',
    PAGE_TITLE_DETAIL: 'Detail Potongan',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
  ATTENDANCE: {
    MENU: 'Absen',
    PAGE_TITLE: 'Absen',
    DESCRIPTION: 'Daftar Absen',
    PAGE_TITLE_CREATE: 'Tambah Absen',
    PAGE_TITLE_EDIT: 'Edit Absen',
    PAGE_TITLE_DETAIL: 'Detail Absen',
    BUTTON_CREATE: 'Tambah',
    BUTTON_SAVE: 'Simpan',
    BUTTON_UPDATE: 'Update',
  },
};
